// Build-time snapshot import. Generated by scripts/dashboard/snapshot.ts.
// In dev, vite watches the JSON and HMRs the dashboard.

import raw from '../../data/snapshot.json';
import type { DashboardSnapshot } from './types';

export const snapshot = raw as DashboardSnapshot;
